cubes:
  - name: products
    sql_table: products

    dimensions:
      - name: product_id
        sql: product_id
        type: string
        primary_key: true

      - name: product_name
        sql: product_name
        type: string

    measures:
      - name: count
        type: count
